### ISSUE TITLE
Disconnected function not being called in MQTT client

### ISSUE THREAD

**Issue by mikeadamz** [adafruit/io-client-python#20] opened 2016-03-12 04:48 UTC
My code is slightly modified from the example:

https://gist.github.com/mikeadamz/024abb04a8092c9cac61

But when I get disconnected, instead of exiting I get this:

```
Publishing 71.6 to GarageTemp.
Publishing 71.6 to GarageTemp.
Publishing 71.6 to GarageTemp.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2287, in _thread_main
    self.loop_forever()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1261, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 811, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1075, in loop_read
    return self._loop_rc_handle(rc)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1382, in _loop_rc_handle
    self.on_disconnect(self, self._userdata, rc)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_IO/mqtt_client.py", line 80, in _mqtt_disconnect
    raise RuntimeError('Unexpected disconnect with rc: {0}'.format(rc))
RuntimeError: Unexpected disconnect with rc: 1

Publishing 71.6 to GarageTemp.
Publishing 71.6 to GarageTemp.
Publishing 71.4866 to GarageTemp.

```

As you can see; no exit and the loop keeps running. The only problem is that any loop iteration after the RunTime error does not make it to Adafruit IO

**Comment by mikeadamz** [comment] 2016-03-12 05:12
Looking at the code

```

    def _mqtt_disconnect(self, client, userdata, rc):
        logger.debug('Client on_disconnect called.')
        self._connected = False
        # If this was an unexpected disconnect (non-zero result code) then raise
        # an exception.
        if rc != 0:
            raise RuntimeError('Unexpected disconnect with rc: {0}'.format(rc))
        # Call the on_disconnect callback if available.
        if self.on_disconnect is not None:
            self.on_disconnect(self)
```

  The on_disconnect function will never be called unless the client was disconnected cleanly (manually?) because any other disconnect will raise an exception before it gets to the on_disconnect invocation.

  How should I reconnect in an error? Do I need to wrap the client.publish in a try/except block?

**Comment by jerbly** [comment] 2016-03-27 10:32
This is a duplicate of #11 - a solution has been provided there but the code not merged yet :(

**Closed** 2017-06-29 19:25 UTC
